### ISSUE TITLE
Redmine 3.4.1.stable settings bad save

### ISSUE THREAD

**Issue by JKeySZR** [team888/redmine-issue_mail_with_attachments-plugin#5]
Hello. 
Setting not correct upload from db in web interface
![image](https://user-images.githubusercontent.com/5275741/30185806-aab295a0-942b-11e7-8feb-9344590b5fcb.png)

In this all field is blank. but in db  is saved

![image](https://user-images.githubusercontent.com/5275741/30185871-f11eb348-942b-11e7-9982-ac586b7f2af0.png)

And if dit settings< for example cheked "Enable mail attachment"
all other form field is empty and in db will be clear :(

---
enable_mail_attachments: 'true'
mail_subject: ''
mail_subject_wo_status: ''
mail_subject_4_attachment: ''

 but must 

---
enable_mail_attachments: 'true'
attach_all_to_notification: 'true'
mail_subject: "[#{issue.project.name} - #{issue.tracker.name} ##{issue.id}] (#{issue.status.name})
  #{issue.subject}"
mail_subject_wo_status: "[#{issue.project.name} - #{issue.tracker.name} ##{issue.id}]
  \ #{issue.subject}"
mail_subject_4_attachment: "[#{issue.project.name} - #{issue.tracker.name} ##{issue.id}]
  |att|"

----------------------------------------- REDMINE info
Environment:
  Redmine version                3.4.1.stable
  Ruby version                   2.1.3-p242 (2014-09-19) [x86_64-linux-gnu]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.15
  Mercurial                      3.1.2
  Cvs                            1.12.12
  Bazaar                         2.6.0
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.12
  issue_mail_with_attachments    0.1.0
  redmine_lightbox2              0.3.2
  time_logger                    0.5.3

**Comment by hhokawa777** [comment]
thanks for your info. could you notice me if you know this issue occurred in other 3.x versions (such as 3.0,3.1,3.2...) too?

**Comment by hhokawa777** [comment]
The issue reproduced on 3.4.1. I will find time to fix it.

**Comment by hhokawa777** [comment]
FIXED on commit https://github.com/team888/redmine-issue_mail_with_attachments-plugin/commit/106957f4a1adbd589e1b9804e5700d57a586dd52
I am going to release with new version 0.2.0.
