### ISSUE TITLE
(Some) Redmine mail headers are suppressed with plugin active

### ISSUE THREAD

**Issue by MegaphoneJon** [team888/redmine-issue_mail_with_attachments-plugin#6]
In `app/models/mailer.rb`, the `issue_add` and `issue_edit` methods call the `redmine_headers` method.  With this plugin installed, headers added by the `redmine_headers` method don't appear on the emails.

I'm not a Ruby person, so I can't tell if that's because `issue_add`/`issue_edit` are never called, or their return values are overwritten, but it seems like a bug?

To replicate:
* Create a new issue in Redmine without the plugin installed.  View the notification email's headers; they include an "X-Redmine-Project" header.
* Install the plugin and create another issue.  The notification email's headers no longer include the "X-Redmine-Project" header.

**Comment by hhokawa777** [comment]
yes, you are right. thank you.
this plugin clear headers after calling issue_add (calling is done by so called monkey-patch: alias_method_chain).
sorry cant fix immediately due to sick these days but solution would be copy redmine_headers lines just before every mail to: .. calls in plugin lib code.

**Comment by hhokawa777** [comment]
the solution for your reported issue is released as v0.9.0 with other funcitionalities. thanks.

**Comment by MegaphoneJon** [comment]
I finally had a chance to test this - I was running with a patched version so I had no urgency, but I wanted to report back.  This new version works great, thank you!
